id: P007892
initial_creation_type: ocr
source_metadata:
  id: bdr:W20503
  title: གསུང་འབུམ། མཁྱེན་རབ་བསྟན་པ་ཆོས་འཕེལ།
  author: ''
  volumes:
    61b3096d9b514844b0f912a7d101b47f:
      image_group_id: I5164
      title: ''
      volume_number: 1
      total_pages: 712
    3b5b4ddc5aec4470b3e5d1077000974b:
      image_group_id: I5165
      title: ''
      volume_number: 2
      total_pages: 616
ebook_metadata:
  title: གསུང་འབུམ། མཁྱེན་རབ་བསྟན་པ་ཆོས་འཕེལ།
  author: ''
  sku: P007892
  cover: cover.jpg
  layers:
  - pagination
